image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 9 x64
  - npm install

build_script:
  - npm run release -- --win

test: off

artifacts:
  - path: 'dist\*.exe'
    name: parity-ui

deploy:
  artifact: 'dist\*.exe'
  auth_token:
    secure: hNnVN2Q/AxSMyi7Rtx7p9xrhIpv923yc2MMj0LnA562ZUKuhnb8Z7oTfxBaPqko9
  draft: true
  on:
    appveyor_repo_tag: true
  provider: GitHub
