image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 9 x64
  - npm install

build_script:
  - npm run test
  - npm run release -- --win

test: off
